_BASE_: [
  "Base-coco-stuff-164K-171.yaml",
]
MODEL:
  META_ARCHITECTURE: "SAN"
  BACKBONE:
    NAME: "D2ClipViTAdapter"
    FREEZE_AT: 0
  CLIP:
    ENABLED: True
    PRETRAINED: True
    NAME: "ViT-B/16"
  SAN:
    CLIP_MODEL_NAME: "ViT-B/16"
    CLIP_PRETRAINED_NAME: "openai"
    FEATURE_LAST_LAYER_IDX: 9
    CLIP_FROZEN_EXCLUDE: ["positional_embedding"]
    CLIP_DEEPER_FROZEN_EXCLUDE: []
    REC_CROSS_ATTN: False
    REC_DOWNSAMPLE_METHOD: "max"
    SOS_TOKEN_FORMAT: "cls_token"
    NUM_CLASSES: 171
    CLIP_TEMPLATE_SET: "vild"
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
  # 启用SAM模块
  SAM:
    ENABLED: True
    CHECKPOINT: "SAN/checkpoint/sam_vit_b_01ec64.pth"
    MODEL_TYPE: "vit_b"
    FROZEN: True
    EXCLUDE_POS: True
    FUSION_TYPE: "add"
  SIDE_ADAPTER:
    NAME: "RegionwiseSideAdapterNetwork"
    VIT_NAME: "vit_w240n6d8_patch16"
    PRETRAINED: False
    IMAGE_SIZE: 640
    DROP_PATH_RATE: 0.0
    NUM_QUERIES: 100
    FUSION_TYPE: "add"
    FUSION_MAP: ["0->0", "3->1", "6->2", "9->3"]
    DEEP_SUPERVISION_IDXS: [7, 8]
    ATTN_BIAS:
      NUM_HEADS: 12
      NUM_LAYERS: 1
      EMBED_CHANNELS: 256
      MLP_CHANNELS: 256
      MLP_NUM_LAYERS: 3
      RESCALE_ATTN_BIAS: True
  FLASH: False
INPUT:
  MIN_SIZE_TRAIN: (640,)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 640
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (640, 640)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 32
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
TEST:
  EVAL_PERIOD: 5000
  AUG:
    ENABLED: False
SOLVER:
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_MULTIPLIER: 0.1
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_EMBED: 0.0
  WEIGHT_DECAY_EMBED_GROUP: [
    "absolute_pos_embed",
    "positional_embedding",
    "pos_embed",
    "query_embed",
    "relative_position_bias_table",
  ]
  MAX_ITER: 60000
  AMP:
    ENABLED: False
WANDB:
  PROJECT: "san"
  NAME: "san_clip_vit_sam_coco"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2 